# Generated by Django 4.0.4 on 2022-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_desc', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=15)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
